# Generated by Django 6.1 on 2026-08-15 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_duration', models.CharField(max_length=20)),
                ('days_per_week', models.PositiveIntegerField()),
                ('equipment_familiarity', models.CharField(max_length=20)),
                ('compound_experience', models.CharField(max_length=20)),
                ('squat_confidence', models.CharField(max_length=20)),
                ('pushup_confidence', models.CharField(max_length=20)),
                ('curl_confidence', models.CharField(max_length=20)),
                ('workout_location', models.CharField(max_length=20)),
                ('structured_program', models.CharField(max_length=10)),
                ('score', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('Starter', 'Starter'), ('Builder', 'Builder'), ('Athlete', 'Athlete')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
