# Generated by Django 6.1 on 2026-08-16 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workoutday_workoutexercise_workoutplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotionCheckAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('squat', 'Squat'), ('bicep_curl', 'Bicep Curl'), ('pushup', 'Push-Up')], max_length=30)),
                ('video', models.FileField(upload_to='motioncheck/')),
                ('rep_count', models.PositiveIntegerField(default=0)),
                ('form_score', models.FloatField(default=0)),
                ('feedback', models.JSONField(blank=True, default=list)),
                ('metric_breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motioncheck_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
