# Generated by Django 6.1 on 2026-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_safemodeprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutday',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
