# Generated by Django 6.1 on 2026-09-18 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='training_experience',
        ),
        migrations.AddField(
            model_name='assessment',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='fitness_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='injuries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='carbohydrates',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='hydration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='plan_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='membership/payments/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='day',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_exercises', to='core.workoutplan'),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='duration_weeks',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='name',
            field=models.CharField(default='X-FIT Workout Plan', max_length=200),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='compound_experience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='curl_confidence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='days_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='equipment_familiarity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='pushup_confidence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='squat_confidence',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='structured_program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='training_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='workout_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='meal_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dietmeal',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='carbs_grams',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='daily_calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='dietary_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='fats_grams',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='protein_grams',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motioncheckanalysis',
            name='exercise',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='motioncheckanalysis',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motioncheckanalysis',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='motioncheck/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workout_days_per_week',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='safemodeprogress',
            name='completed_modules',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='day_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='theme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workoutday',
            name='week_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.workoutday'),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='MotionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(choices=[('squat', 'Squat'), ('pushup', 'Push Up'), ('bicep_curl', 'Bicep Curl')], max_length=30)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='motioncheck/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motion_checks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
