# Generated by Django 6.1 on 2026-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_profile_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='fitness_level',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='injuries',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='training_experience',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='compound_experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='curl_confidence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='equipment_familiarity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='pushup_confidence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='squat_confidence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='structured_program',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='training_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='workout_location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dietary_preference',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(blank=True, choices=[('fat_loss', 'Fat Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength'), ('general_fitness', 'General Fitness')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workout_days_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
