# Generated by Django 6.1 on 2026-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('category', models.CharField(choices=[('tshirts', 'T-Shirts'), ('compression', 'Compression'), ('hoodies', 'Hoodies'), ('shorts', 'Shorts'), ('accessories', 'Accessories'), ('bags', 'Bags')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('sizes', models.JSONField(blank=True, default=list)),
                ('material', models.CharField(blank=True, max_length=255)),
                ('fit', models.CharField(blank=True, max_length=255)),
                ('features', models.JSONField(blank=True, default=list)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
