# Generated by Django 6.1 on 2026-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='payment_screenshot_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_screenshot_name',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='payment_screenshot_type',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
